name: test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      dynamodb-local:
        image: amazon/dynamodb-local:7ef4a2c45b58c2901e70a4f28e0953a422c2c631baaaf5e2c15e0805740c7752
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run-script lint

      - name: test
        run: npm run-script test
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: .tap/report/lcov.info
